name: Deploy to shinyapps.io

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy to (staging or production)'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install rsconnect
      run: R -e 'install.packages("rsconnect")'

    - name: Deploy app
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        DEPLOY_ENV: ${{ github.event.inputs.environment }}
      run: |
        R -e 'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
        R -e '
          app_name <- ifelse( Sys.getenv("DEPLOY_ENV") == "production",  "bmp_wq_index_app", "bmp_wq_index_app_staging");
          message("Deploying to: ", app_name);
          rsconnect::deployApp(appDir = ".", appName = app_name)
        '
